### ISSUE TITLE
Add `chat_type` and `chat_instance` properties to `InitData` in `@tma.js/init-data`

### ISSUE THREAD

**Issue by gut4** [Telegram-Mini-Apps/tma.js#112]
missed params ```chat_type``` and ```chat_instance``` in InitData

https://docs.telegram-mini-apps.com/docs/launch-params/init-data#parameters-list
https://core.telegram.org/bots/webapps#webappinitdata

**Comment by heyqbnk** [comment]
Update released. Please, bump your deps. Thank you for report!
