### ISSUE TITLE
Settings button in the menu

### ISSUE THREAD

**Issue by yelnar** [Telegram-Mini-Apps/tma.js#115]
**Is your feature request related to a problem? Please describe.**

Currently, when I click the menu button on the top right corner I can only see "Reload Page" option.

**Describe the solution you'd like**

I would like to add "Settings" button there, that opens settings page.

**Describe alternatives you've considered**

I can add that button somewhere on the screen, but putting it inside that menu seems more appropriate.

**Comment by heyqbnk** [comment]
Hey. As far as I know, this feature will be unlocked for your application in case, you are Telegram Ads major advertiser

**Comment by heyqbnk** [comment]
I am now thinking about new method Telegram added in one of the latest updates. They probably allowed all developers to use this feature, but I am not sure. There were no public announcements related to this topic, we are still waiting

**Comment by yelnar** [comment]
Thanks for clarification! Would be nice if they could allow that for all app developers.

**Comment by heyqbnk** [comment]
We should wait for v6.10 and check if new Settings button released method is available to everybody
