### ISSUE TITLE
chat_type, chat_instance properties still broken

### ISSUE THREAD

**Issue by gut4** [Telegram-Mini-Apps/tma.js#122]
I tried latest version but still can't get ```chat_type``` and ```chat_instance```

Also types are missed:
```
Property 'chatInstance' does not exist on type 'InitData'
Property 'chatType' does not exist on type 'InitData'
```
Looks like something wrong here:
https://github.com/Telegram-Mini-Apps/tma.js/blob/master/packages/sdk/src/components/InitData/InitData.ts

**Comment by heyqbnk** [comment]
Sorry, I updated only `@tma.js/init-data`, but forgot about SDK. SDK update released, check it out please
