### ISSUE TITLE
Rework SDK for React

### ISSUE THREAD

**Issue by heyqbnk** [Telegram-Mini-Apps/tma.js#134]
It is currently not that comfortable to use SDK for React. There could be at least several cases when forcing React to call re-render with the same component instance is a bad idea. 

For example, `useThemeParams` returns the same instance of `ThemeParams` which will not work fine when it is being passed as a dependency to some hook like `useEffect`. React will just not see the changes.

I need more feedback for this task to start working on rework.

**Comment by vkruglikov** [comment]
Hi, you can use [`themeChanged`](https://core.telegram.org/bots/webapps#events-available-for-mini-apps) event of WebApp for listening changes

**Comment by heyqbnk** [comment]
The solution I see now is that the package should provide the following:

1. Reactive SDK components. All generated reactive values should be new instances of their classes. This will make React reactive system work properly. This opportunity (to create new instances) appeared some updates ago.
2. Re-exported utilities from the SDK. So the developer would not need to install SDK. Despite the fact, that each package in our ecosystem is responsible for its own functionality, this looks like an exception

**Comment by heyqbnk** [comment]
Moved to the discussion: https://github.com/Telegram-Mini-Apps/tma.js/discussions/155
