### ISSUE TITLE
Fix navigator restoration mechanism

### ISSUE THREAD

**Issue by heyqbnk** [Telegram-Mini-Apps/tma.js#150]
Navigator restoration will not work in Telegram Web as long as web version recreates whole iframe breaking browser history. We should probably restore from the sessionStorage then.

Could take such implementation from the SDK.

**Comment by Razzwan** [comment]
It seems quite important issue. Not possible to work with such state of library

**Comment by heyqbnk** [comment]
> It seems quite important issue. Not possible to work with such state of library

Solution is ready, but I would like to improve it. It will be released in a next few days as a major update with package docs

**Comment by heyqbnk** [comment]
Should be fixed in the latest major release.

- [Package documentation](https://docs.telegram-mini-apps.com/packages/typescript/tma-js-navigation#tma-js-navigation)
- [Complex example](https://docs.telegram-mini-apps.com/packages/typescript/tma-js-navigation#example)
