### ISSUE TITLE
@tma.js/sdk-react: lacking parameter `initData.user.allows_write_to_pm`

### ISSUE THREAD

**Issue by di-sukharev** [Telegram-Mini-Apps/tma.js#156]
**Platform**

Select one of the following:

- [x] Telegram for Android
- [x] Telegram for iOS
- [x] Telegram for macOS
- [x] Telegram Desktop
- [x] Telegram Web A
- [x] Telegram Web K

**Describe the bug**

This example:
```
import { validate } from '@tma.js/init-data-node';

const secretToken = '5768337691:AAH5YkoiEuPk8-FZa32hStHTqXiLPtAEhx8';
const initData =
  'query_id=AAHdF6IQAAAAAN0XohDhrOrc' +
  '&user=%7B%22id%22%3A279058397%2C%22first_name%22%3A%22Vladislav%22%2C%22last_name%22%3A%22Kibenko%22%2C%22username%22%3A%22vdkfrost%22%2C%22language_code%22%3A%22ru%22%2C%22is_premium%22%3Atrue%7D' +
  '&auth_date=1662771648' +
  '&hash=c501b71e775f74ce10e377dea85a7ea24ecd640b223ea86dfe453e0eaed2e2b2';

validate(initData, secretToken);
```

Which i found [Here](https://docs.telegram-mini-apps.com/docs/libraries/tma-js-init-data-node) lacks `allows_write_to_pm` parameter, and always returns `Invalid signature` error when calling `validate()` without `allows_write_to_pm`.

It happens that there is no `allows_write_to_pm` parameter on the `const initData = useInitData()`, but when i attach the official Telegram SDK via a script link and read the `window.Telegram.initData`, then `allows_write_to_pm` is present on the `user` object.

**To Reproduce**

1. Go to https://docs.telegram-mini-apps.com/docs/libraries/tma-js-init-data-node
2. Copy/paste code example into your app
3. Run the `validate()` method
4. Get `Invalid signature` error, because you don't pass `allows_write_to_pm` and there is none in tma.js

**Expected behavior**

```
import { useInitData } from "@tma.js/sdk-react";

const initData = useInitData()
console.log(initData.user.allowsWriteToPm)
// outputs true/false or null
```

**Comment by heyqbnk** [comment]
It seems like you have mixed up some not connected with each other problems. Here is the answer:

1. `@tma.js/sdk-react` has nothing to do with what you are requesting.
2. In case, you need raw representation of init data (you do), you have to use `useSDK` hook. Yeah, it seems like I forgot to add special hook to retrieve init data initial representation. Here is your code:
```typescript
import { useSDK } from '@tma.js/sdk-react';

function MyComponent() {
  const { components } = useSDK();

  if (components && components.initDataRaw) {
    // Here is your init data raw representation. It will contain missing parameters.
    // Don't forget, it can be missing.
    const initDataRaw = components.initDataRaw;
  }
}
```
3. Example in `@tma.js/init-data-node` does not depend on parameters added by Telegram in the future. It just shows how you could use validation function. It should work with any set of parameters as long as it uses generic flow. This example will surely work when you start using `initDataRaw` and pass it to your server.
4. Yeah, `@tma.js/init-data` and `@tma.js/sdk` are missing these parameters. You don't really need them in this case exactly, but I will add them in the next update. Let me know if you need them right now for purposes not connected to init data validation.

I created separate issues for your problem:
- Missing init data properties: https://github.com/Telegram-Mini-Apps/tma.js/issues/157
- Missing hook to get raw init data representation: https://github.com/Telegram-Mini-Apps/tma.js/issues/158

I would also appreciate sharing your ideas on how to make SDK for React better in public discussion: https://github.com/Telegram-Mini-Apps/tma.js/discussions/155

**Comment by di-sukharev** [comment]
PERFECT, FAST, WHAT A MAINTAINER x1000 <3
