### ISSUE TITLE
Add missing theme parameters and rework related logic with CSS variables

### ISSUE THREAD

**Issue by heyqbnk** [Telegram-Mini-Apps/tma.js#168]
Telegram is going to add new theme parameters. This is the reason to add them on our packages.

Nevertheless, the problem is we want next new theme parameters to appear automatically as CSS variables.

**Comment by thecoorum** [comment]
As far as I understood from the package code you have a static list of variables you are watching to transform to internal CSS variables then, right? What do you think about generating the list based on the `-color` postfix in the Telegram SDK variables? I will try to create a PR with a proposal later today

**Comment by heyqbnk** [comment]
We don't use Telegram SDK. The purpose of these packages is to avoid doing it. You can learn more about it in this [document](https://github.com/Telegram-Mini-Apps/tma.js/blob/master/MOTIVATION.md).

The solution is rather easy. We have to rework `init` function in `@tma.js/sdk` to make it work with the dynamic list of theme parameters

**Comment by thecoorum** [comment]
Yeah, just got to this document. Thanks for your help and for developing an amazing library!
