### ISSUE TITLE
`MainButton` is not clickable on iOS

### ISSUE THREAD

**Issue by thecoorum** [Telegram-Mini-Apps/tma.js#171]
**Platform**

Select one of the following:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [x] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

**Describe the bug**

**To Reproduce**

1. Mount the button with `@tma.js/sdk-react` with the following code
```
const onSubmit = useCallback((values: zod.infer<typeof schema>) => {
  // ...
}, []);

useEffect(() => {
  mainButton.setText("Зберегти");
  mainButton.on("click", form.handleSubmit(onSubmit));

  return () => {
    mainButton.hide();
    mainButton.off("click", form.handleSubmit(onSubmit));
  };
  // eslint-disable-next-line react-hooks/exhaustive-deps
}, [onSubmit]);
```
2. Try to press the button and see nothing happened

**Expected behavior**

The button calls the callback passed to `mainButton.on('click')`

**Comment by heyqbnk** [comment]
Have you called `mainButton.enable()`?

**Comment by thecoorum** [comment]
I was missing `mainButton.enable()`. Now it's working, thanks!. Strange that it was working in macOS without calling it
