### ISSUE TITLE
Initializing the SDK (Vue 3, Vite, TypeScript) throws an error

### ISSUE THREAD

**Issue by I-grok-I** [Telegram-Mini-Apps/tma.js#188]
I was trying to follow the instructions from the docs:
I installed @tma.js/sdk (0.13.3)
Then pasted this code into my Vue app like so: 

```
import { init } from '@tma.js/sdk';

init().then(components => {
    const { mainButton, viewport } = components;
    mainButton.on('click', () => viewport.expand());
    mainButton
        .setBackgroundColor('#ff0000')
        .setTextColor('#ffffff')
        .setText('Expand')
        .enable()
        .show();
});
```

I am using Telegram's test environment so that I can use the tma without ssl protocol. 

So when I open up the app I see:
1) no main button there
2) if i check the browser and inspect the console I can see the Error with the following text:
```
Uncaught (in promise) Error: Unable to retrieve any launch parameters. []
at R2 (computeLaunchData.ts:94:9)
    at T2 (retrieveLaunchData.ts:21:22)
    at Dt (init.ts:62:42)
    at Jt (init.ts:166:22)
    at setup (App.vue:16:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7289:25)
    at setupComponent (runtime-core.esm-bundler.js:7250:36)
    at mountComponent (runtime-core.esm-bundler.js:5646:7)
    at processComponent (runtime-core.esm-bundler.js:5612:9)
```

### Steps to reproduce the behavior:
1. install the packaje with "npm i @tma.js/sdk"
2. run tma locally with Telegram on test environment (https://docs.telegram-mini-apps.com/platform/test-environment)
3. paste in your root component the code:
```
import { init } from '@tma.js/sdk';

init().then(components => {
    const { mainButton, viewport } = components;

    mainButton.on('click', () => viewport.expand());

    mainButton
        .setBackgroundColor('#ff0000')
        .setTextColor('#ffffff')
        .setText('Expand')
        .enable()
        .show();
});
```
4. See no mainButton there

### Expected behavior

I expected to see the main button

![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/117625419/c633fe94-6bf8-43a1-83dd-e595c3a0cff4)
![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/117625419/50c4905b-10a4-46f7-9704-7fa1c0ff3622)

**Comment by heyqbnk** [comment]
I am not familiar with Vue, but is there any chance, Vue application rewrites current location hash?

**Comment by I-grok-I** [comment]
The community say that the hash doesn't change when u do not use Router. I'm not using Router at the moment

**Comment by heyqbnk** [comment]
Ok, I will re-check `retrieveLaunchData` code today. I will probably need a reproduction example from you in case I am not be able to reproduce the problem

**Comment by heyqbnk** [comment]
Well, I was unable to reproduce this problem. Could you contact me in Telegram (t.me/vdkfrost), so we could discuss the problem and look into it in real time. I don't really get how it is possible for this problem to even exist. The only assumption is you use something like IE 9, but I am not sure.

Or you could create a repro example
