### ISSUE TITLE
Bug: 'Edit this page on GitHub' does not work

### ISSUE THREAD

**Issue by scffs** [Telegram-Mini-Apps/tma.js#199]
for example: [page](https://docs.telegram-mini-apps.com/packages/typescript/tma-js-sdk/methods-and-events)
after click [Edit this page on GitHub](https://github.com/telegram-mini-apps/tma.js/edit/master/apps/docs/src/packages/typescript/tma-js-sdk/methods-and-events.md):

![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/67464545/ec43c9d4-2e75-4a96-af38-43261c15cf8f)

**Comment by heyqbnk** [comment]
Fixed. Thank you!
