### ISSUE TITLE
docs: get 404 when go to page by search

### ISSUE THREAD

**Issue by scffs** [Telegram-Mini-Apps/tma.js#221]
1. write something in the search input and go to any page

![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/67464545/e6995846-3302-417c-b660-4bf33ccbad53)

![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/67464545/5db81a7f-7492-48b2-9eaa-179926b1f17f)

https://docs.telegram-mini-apps.com/

**Comment by heyqbnk** [comment]
Thank you for report! Seems like something is wrong with Algolia. I temporarily switched to another search engine and cleared Algolia cache. We will have to wait about a week for re-indexing, but search should be working fine now
