### ISSUE TITLE
[Bug]: installation fails when trying to run npx script

### ISSUE THREAD

**Issue by I-grok-I** [Telegram-Mini-Apps/tma.js#270]
### Telegram Application

Telegram for iOS, Telegram for macOS, Telegram Desktop

### Describe the Bug

When i run "npx @tma.js/create-mini-app " after i specify directory name it shows this:
<img width="937" alt="Снимок экрана 2024-03-29 в 16 12 15" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/117625419/7d84bd62-571c-4bd7-bb9f-4c9dcffe1703">

and nothing happens until i press "return" (aka "Enter") button.

Then it returns Error:
<img width="588" alt="Снимок экрана 2024-03-29 в 16 13 57" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/117625419/dc502769-6e6e-4c56-8aac-ab5288d0a05d">

What could cause the problem ?

### To Reproduce

1. Go to https://docs.telegram-mini-apps.com/packages/tma-js-sdk and copy installation terminal script from there.
2. Go to NodeJS and navigate to any directory, then run the script that you've copied in step 1.
3. Follow wizard instructions

### Expected Behavior

I expected to get the boilerplate initialized successfully

**Comment by heyqbnk** [comment]
We already got some developer having similar issue. He then wrote back that there was something wrong with his local git utility configuration

**Comment by I-grok-I** [comment]
@heyqbnk should i have already initialized git repository before running the npx script in terminal ?

**Comment by heyqbnk** [comment]
> @heyqbnk should i have already initialized git repository before running the npx script in terminal ?

Nope. Under the hood, this utility just uses the command like 'git clone ...'. You could try doing the same with reactjs-template

**Comment by heyqbnk** [comment]
Here is the possible solution for your problem:
https://askubuntu.com/questions/45679/ssh-connection-problem-with-host-key-verification-failed-error

**Comment by heyqbnk** [comment]
I have added a new update which makes CLI try to use repository HTTPS link first and then SSH link. This can also solve your problem
