### ISSUE TITLE
[Bug]: react-router-dom params with react-router-integration

### ISSUE THREAD

**Issue by hiendaovinh** [Telegram-Mini-Apps/tma.js#276]
### Telegram Application

Other

### Describe the Bug

Hi,
I was looking for a way to use react-router-dom route with params as mini app URL but it's impossible because of the HashNavigator implementation.
Routes
```
[{
  path: "/foo/:param",
  Component: Comp
}]
```

There is no way to set `https://127.0.0.1:5173/reactjs-template/#/foo/bar` as the application URL.

### To Reproduce

1. `pnpm dlx @tma.js/create-mini-app`
2.
```
Language
❯◉ TypeScript
 ◯ JavaScript
SDK
 ◉ tma.js
 ◯ Telegram SDK
Framework
 ◉ React.js
 ◯ Solid.js
 ◯ Next.js
 ```
4. `pnpm i`
5. Setup SSL for the dev server with `@vitejs/plugin-basic-ssl`
6. Use `https://127.0.0.1:5173/reactjs-template/#/foo/bar` as the application URL.

### Expected Behavior

HashNavigator should persist the navigation state using the URL instead of the sessionStorage to make routes accessible.

**Comment by heyqbnk** [comment]
Do I get it right, that you would like to pass initial routing entries? I assume, the problem is in this line:
https://github.com/Telegram-Mini-Apps/tma.js/blob/master/packages/react-router-integration/src/createNavigator.ts#L21

When we see, that page was not reloaded, we should not create a navigator with empty entries, but take a look at current hash

**Comment by hiendaovinh** [comment]
Btw, it's easier to reproduce by visiting the mini app directly `https://127.0.0.1:5173/#tgWebAppData=...` and observe the URL changes.

**Comment by hiendaovinh** [comment]
> The only problem now is to keep telegram launch params when using <Link> to navigate.

Well this is more complicated than I thought. 
```
# 1, navigate to this, render fine
https://127.0.0.1:5173/#/theme-params?tgWebAppData=user...

# 2, remove the launch params, render fine
https://127.0.0.1:5173/#/theme-params

# 3, change router path, Error: Unable to determine current environment and possible way to send event.
https://127.0.0.1:5173/#/launch-params
```

**Comment by hiendaovinh** [comment]
Thanks for your pointer.

**Comment by heyqbnk** [comment]
Hey. I have just released a major update for tma.js ecosystem and worked a bit on the navigation utils. Could you try checking an updated version of the [React template](https://github.com/Telegram-Mini-Apps/reactjs-template)? Does it work fine for you now?
