### ISSUE TITLE
[Bug]: Incorrect css variable name

### ISSUE THREAD

**Issue by meowcorp** [Telegram-Mini-Apps/tma.js#285]
### Telegram Application

Telegram for iOS, Telegram Desktop

### Describe the Bug

Hello, im using @tma.js/sdk-react with TelegramUI library and have problems with bg-color variable. tma.js attaching `--tg-background-color` and `--tg-theme-background-color` instead of `--tg-theme-bg-color` (which is described in the telegram documentation). This causes TelegramUI to display the fallback instead of the theme color.
<img width="439" alt="Screenshot 2024-04-23 at 15 34 48" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/45810834/999294cf-f7fc-4764-883e-23ecb90828f3">

### To Reproduce

1. Install @tma.js/sdk-react and @tma.js/sdk
2. Check html css variables

### Expected Behavior

There must be a --tg-theme-bg-color variable and --tg-theme-secondary-bg-color

**Comment by novikdev** [comment]
While we are waiting @tma.js/sdk@3.0 there is a workaround:

```css
:root {
  --tg-theme-bg-color: var(--tg-theme-background-color);
}
```

**Comment by heyqbnk** [comment]
Hey. A new major version of SDK was released and your problem should be solved now. I currently have no docs for it and will add it soon. 

New CSS variable name must be `--tg-theme-bg-color`. Additionally, you can generate the CSS variable name by yourself. 

Function source code:
https://github.com/Telegram-Mini-Apps/tma.js/blob/master/packages/sdk/src/css-vars/bindThemeParamsCSSVars.ts

As long as there is no such function as `init` anymore, you have to call `bindThemeParamsCSSVars` by yourself. In case, you have problems understanding what to do, refer the [React template](https://github.com/Telegram-Mini-Apps/reactjs-template).
