### ISSUE TITLE
[Bug]: Expo Web with Metro bundler - any imported from "@tma.js/sdk" function or variable is undefined

### ISSUE THREAD

**Issue by rodnoycry** [Telegram-Mini-Apps/tma.js#287]
### Telegram Application

Other

### Describe the Bug

Trying to import any functions or variables from "@tma.js/sdk" in project that uses metro bundler ends up in the next behavior: every imported function or variable is undefined

After some investigation I found out that this problem caused by `"browser"` key in package.json of package. When I deleted this key with specified `"./dist/index.iife.js"` from my `node_modules/@tma.js/sdk/package.json` all imports started work correctly. I believe there is some conflict with "browser" key with metro bundler

I understand that this is probably very specific problem, and if there will be no solution I suggest to use package-patch for anyone that will encounter same issue

**node_modules/@tma.js/sdk/package.json**
```diff
   "main": "./dist/index.cjs",
-  "browser": "./dist/index.iife.js",
   "module": "./dist/index.mjs",
   "types": "./dist/dts/index.d.ts",
```

### To Reproduce

1. Create project using expo, that uses metro bundler
```sh
npx create-expo-app example-app
```
2. Install @tma.js/sdk
```sh
npm install "@tma.js/sdk"
```
3. Import any function from "@tma.js/sdk" and try to use it in web development mode
```tsx
/* in App.jsx */
import { init } from "@tma.js/sdk"

console.log({ init })
```
4. Run expo web development build
```sh
npm run web
```
5. Wait for the build, open http://localhost:8081 and check console
```js
{ init: undefined }
```

### Expected Behavior

Correct import

**Comment by heyqbnk** [comment]
Did I get it right, that removing the `browser` property solves the problem for you?

**Comment by rodnoycry** [comment]
> Did I get it right, that removing the `browser` property solves the problem for you?

Yes, you are right

**Comment by heyqbnk** [comment]
Ok. This field will be removed in v3.0. We don't really need it and created only for jsdelivr. Well, jsdelivr will work fine even without this field

**Comment by rodnoycry** [comment]
> Ok. This field will be removed in v3.0. We don't really need it and created only for jsdelivr. Well, jsdelivr will work fine even without this field

Thank you!

**Comment by heyqbnk** [comment]
Issue should be fixed in the latest major update. Let me know if it doesn't fit you.
