### ISSUE TITLE
[Bug]: UI at the bottom of the app sometimes disappears.

### ISSUE THREAD

**Issue by flagg2** [Telegram-Mini-Apps/tma.js#289]
### Telegram Application

Telegram for iOS

### Describe the Bug

When I programatically call viewport.expand() while working with a miniapp, the UI disappears too soon when scrolling

An example of this happening (the heading at the bottom disappears):
https://github.com/Telegram-Mini-Apps/tma.js/assets/65034737/4dbd18dd-f458-4de8-85ca-20aa7f7583c9

The issue is not present if I resize the viewport manually. Tested on ios and mac, only happens on ios (dont konw about android)

### To Reproduce

- have a miniapp with larger ui than is the screen height (a scrollable container)
- call .expand() programatically
- watch the ui at the bottom of screen flicker / disappear 

### Expected Behavior

The UI should remain visible as long as it is on the screen.

**Comment by heyqbnk** [comment]
Hey. 

Not related to tma.js. Described problem is related to iOS Web View specific problems. As far as I remember, it is somehow connected with using position sticky, fixed, or something like that
