### ISSUE TITLE
[Feature]: send message to user/group in mini app

### ISSUE THREAD

**Issue by guotie** [Telegram-Mini-Apps/tma.js#291]
### Is your feature request related to a problem? Please describe.

send message/link to user/group in mini app, when user or group user click the link, the user will be launch the mini app.

### Describe the solution you'd like

send message/link to user/group in mini app, when user or group user click the link, the user will be launch the mini app.

### Describe alternatives you've considered

we cannot do such things currently, which is very import for mini-app to reach more people

**Comment by guotie** [comment]
In wechat, we can send link to user in wechat's mini-program

**Comment by heyqbnk** [comment]
You can use the share links to implement the functionality you need:
https://core.telegram.org/api/links#share-links

In your case such a link could be
```
t.me/share?url=t.me%2Fmybot%2Fmyapp&text=Check%20this%20app
```

**Comment by guotie** [comment]
but share link cannot send from mini-app to a chat/chat group

**Comment by heyqbnk** [comment]
> but share link cannot send from mini-app to a chat/chat group

Why not? You should open the `openTelegramLink` method and pass this link there

https://docs.telegram-mini-apps.com/packages/tma-js-sdk/components/utils#opentelegramlink

**Comment by guotie** [comment]
Okey, I'll try it
