### ISSUE TITLE
[Bug]: new version @tma.js/sdk-react don't have re-export `DisplayGate`

### ISSUE THREAD

**Issue by HzDev3628** [Telegram-Mini-Apps/tma.js#294]
### Telegram Application

Other

### Describe the Bug

Hi! @heyqbnk 
If you install a new version `@tma.js/sdk-react` then there is no re-export in the index file `DisplayGate`
What produces an error.

new version:
<img width="1047" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/130896079/644e2885-24e8-484a-a957-3647f0dc15be">

older version:
<img width="716" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/130896079/191d6aeb-7c4a-450e-970a-8b3a0e209b10">

### To Reproduce

1. install the last version 
2. try import `DisplayGate` from `@tma.js/sdk-react`
4. See error `Module '"@tma.js/sdk-react"' has no exported member 'DisplayGate'.ts(2305)`

### Expected Behavior

I want re-export back `DisplayGate` so that users can continue to use the latest versions of this package.

**Comment by HzDev3628** [comment]
> I think it was remove intentionally. If you look at the release logs.

How then to use `DisplayGate` the latest version?

**Comment by heyqbnk** [comment]
Documentation related to this topic has just released. Check this out!
https://docs.telegram-mini-apps.com/packages/tma-js-sdk-react
