### ISSUE TITLE
[Bug]: Cannot resolve symbol 'init' 

### ISSUE THREAD

**Issue by longqingzhao** [Telegram-Mini-Apps/tma.js#295]
### Telegram Application

Other

### Describe the Bug

when I use init,it report Cannot resolve symbol 'init' 

### To Reproduce

import: import { init }  from '@tma.js/sdk';
error: Cannot resolve symbol 'init' 

### Expected Behavior

can use init

**Comment by heyqbnk** [comment]
Hey! I have released a new major version of the package which now doesn't have this function.

I will add a related patch note in the next few days. Until then, take a look at the templates, which were updated according to the changes done in the new major version:

https://github.com/orgs/Telegram-Mini-Apps/repositories

**Comment by longqingzhao** [comment]
ok thank you

**Comment by longqingzhao** [comment]
I have saw some templates, But I want to expand sreen, I cannot find how to expand.

**Comment by heyqbnk** [comment]
In case, you would like to use it in components-manner, use this code:
```
import { initViewport } from '@tma.js/sdk';

const viewport = await initViewport();
viewport.expand();
```

**Comment by longqingzhao** [comment]
ok thanks!

**Comment by heyqbnk** [comment]
Documentation related to this topic has just released. Check this out!
https://docs.telegram-mini-apps.com/packages/tma-js-sdk-react
