### ISSUE TITLE
Fix documentation links

### ISSUE THREAD

**Issue by Desiders** [Telegram-Mini-Apps/tma.js#315]
### Is your feature request related to a problem? Please describe.

Currently, all links in `README.md` are directs to error 404

### Describe the solution you'd like

Replace these links with links to packages (https://docs.telegram-mini-apps.com/packages)

**Comment by heyqbnk** [comment]
Hey! Didn't quite get about which `README.md` file exactly we are talking about. I have probably already fixed this issue not really long time ago

**Comment by Desiders** [comment]
> Hey! Didn't quite get about which `README.md` file exactly we are talking about

For example text and documentation link from https://github.com/Telegram-Mini-Apps/tma.js/blob/master/README.md#tmajsinit-data-node:

The package provides utilities to work with the initialization data of Telegram Mini Apps on the server side. To learn more about the initialization data and its usage, please refer to the [documentation](https://docs.telegram-mini-apps.com/platform/launch-parameters/common-information).

Here `documentation` are directs to missing page

**Comment by heyqbnk** [comment]
Thank you for report. Fixed. Let me know if something is still wrong
