### ISSUE TITLE
[Bug]: DisplayGate from "@tma.js/sdk-react";

### ISSUE THREAD

**Issue by gsw85** [Telegram-Mini-Apps/tma.js#320]
### Telegram Application

Telegram Desktop

### Describe the Bug

The error is on DisplayGate:
Attempted import error: 'DisplayGate' is not exported from '@tma.js/sdk-react' (imported as 'DisplayGate').

### To Reproduce

````
import { SDKProvider, DisplayGate } from "@tma.js/sdk-react";

function SDKProviderError({ error }) {
  return (
    <div>
      Oops. Something went wrong.
      <blockquote>
        <code>
          {error instanceof Error
            ? error.message
            : JSON.stringify(error)}
        </code>
      </blockquote>
    </div>
  );
}


function SDKProviderLoading() {
  return <div>SDK is loading.</div>;
}

function SDKInitialState() {
  return <div>Waiting for initialization to start.</div>;
}

export function TmaSDKLoader({ children }) {
  return (
    <SDKProvider
      options={{
        async: true,
        complete: true,
      }}
    >
      <DisplayGate
        error={SDKProviderError}
        loading={SDKProviderLoading}
        initial={SDKInitialState}
      >
        {children}
      </DisplayGate>
    </SDKProvider>
  );
}
````

### Expected Behavior

Expect to run normall and get the telegram data from user

**Comment by heyqbnk** [comment]
Hey. There is no such component as `DisplayGate` anymore. You can now see how it works in [React](https://github.com/Telegram-Mini-Apps/reactjs-template) and [Next](https://github.com/Telegram-Mini-Apps/nextjs-template) templates.

Documentation will be released soon

**Comment by heyqbnk** [comment]
Documentation related to this topic. Check this out!
https://docs.telegram-mini-apps.com/packages/tma-js-sdk-react
