### ISSUE TITLE
[Bug]: React SDK. `useThemeParams`'s result isn't being updated

### ISSUE THREAD

**Issue by alagunoff** [Telegram-Mini-Apps/tma.js#344]
### Telegram Application

Telegram Desktop

### Describe the Bug

 I assume that when colors are being changed in the super app the resulting object from the hook should also be updated but it is not

### To Reproduce

*Assumed that we use this hook somewhere in our app and set, for example, `textColor` from the result to some element.*

1. Open mini app
2. Change color scheme in the mini app
3. Nothing happens in the mini app

### Expected Behavior

Result of the `useThemeParams` hook is always up-to-date. Meaning that color of the text, in our case, is being updated instantaneously

**Comment by heyqbnk** [comment]
I wasn't able to reproduce the problem.

Make sure, you are using the latest version of the package.
- Checked in the mini application [here](https://t.me/tmajsbot/react_example?startapp=debug)
- This mini app [source code](https://github.com/Telegram-Mini-Apps/reactjs-template/blob/master/src/pages/ThemeParamsPage/ThemeParamsPage.tsx) working with theme

Changing theme in Telegram desktop updates the colors inside the mini app
