### ISSUE TITLE
[Bug]: React SDK. `useLaunchParams` doesn't work with ssr

### ISSUE THREAD

**Issue by alagunoff** [Telegram-Mini-Apps/tma.js#347]
### Telegram Application

Telegram Desktop

### Describe the Bug

The hook doesn't have `ssr` parameter like, for example, `useInitData`. Therefore, while we build next.js app where the hook is used we get error saying "Error: Unable to retrieve launch parameters from any known source."

### To Reproduce

1. Use `useLaunchParams` hook somewhere in the next.js app
2. Start build process
3. Get build error

### Expected Behavior

The hook has `ssr` parameter and doesn't cause build crash like other hooks

**Comment by GrayJyy** [comment]
i got the same error,how can i fix it?

**Comment by heyqbnk** [comment]
TBD this week

**Comment by alagunoff** [comment]
> i got the same error,how can i fix it?

The problem is in the code's execution on the server. So, one of the possible solutions is using [lazy loading](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading) from next.js

**Comment by heyqbnk** [comment]
Released in @tma.js/sdk-react@2.2.4
