### ISSUE TITLE
[Feature]: Support Web Crypto API in @tma.js/init-data-node

### ISSUE THREAD

**Issue by heyqbnk** [Telegram-Mini-Apps/tma.js#348]
### Is your feature request related to a problem? Please describe.

Node native modules are not supported in some environments. For example, in [Vercel's Edge runtime](https://nextjs.org/docs/pages/api-reference/edge). 

### Describe the solution you'd like

We could provide another one entry point for the web crypto and use it this way:

```ts
import { validate } from '@tma.js/init-data-node/web';

await validate(...);
```

### Additional context

This issue is a continuation of the https://github.com/Telegram-Mini-Apps/tma.js/pull/345 PR

**Comment by focus-at** [comment]
On cloudflare workers:
```
Could not resolve "node:crypto"
Could not resolve "node:url"
```
