### ISSUE TITLE
[Feature]:  How can I realize this functionality with your package? React

### ISSUE THREAD

**Issue by virus231** [Telegram-Mini-Apps/tma.js#361]
### Is your feature request related to a problem? Please describe.

https://github.com/Telegram-Mini-Apps/tma.js/assets/46872670/f0cec4ea-5ad8-42a3-8563-adb00d0ad3e0

### Describe the solution you'd like

I would to get the solution with your package, please

**Comment by heyqbnk** [comment]
I have already answered you in developers chat.

https://docs.telegram-mini-apps.com/packages/tma-js-sdk/components/mini-app#access-requests
