### ISSUE TITLE
[Bug]: When opening the bot webpage on an Android mobile device, performing screen interactions such as clicking and swiping causes script error.

### ISSUE THREAD

**Issue by ahustcer** [Telegram-Mini-Apps/tma.js#367]
### Telegram Application

Telegram for Android

### Describe the Bug

When opening the bot webpage on an Android mobile device, performing screen interactions such as clicking and swiping causes script error.

### To Reproduce

In my React project, when the bot connects to my webpage and screen interactions occur, a script error overlay appears. This issue only occurs on Android mobile devices.

### Expected Behavior

I would like to seek some help (I have already used es-module-shims for compatibility)

**Comment by heyqbnk** [comment]
Any information on what error occurs exactly?

**Comment by ahustcer** [comment]
![error](https://github.com/Telegram-Mini-Apps/tma.js/assets/128986994/91f1c0f5-d372-42e8-8c21-85145ee6f9b2)
like this    screen interactions such as clicking and swiping

**Comment by heyqbnk** [comment]
I am not sure, this is related to tma.js. Check the code if it has some unhandled errors
