### ISSUE TITLE
[Feature]: Improve security by allowing to pass token's hmac hash instead of token

### ISSUE THREAD

**Issue by snimshchikov** [Telegram-Mini-Apps/tma.js#371]
### Is your feature request related to a problem? Please describe.

I want to minimize the number of places where I need to provide bot token.

### Describe the solution you'd like

an option skip_token_hashing added to ValidateOptions (or something like this)

### Additional context

Bot's token is always encoded with hmac sha256 function with the same key. It is possible to check data authenticity just by providing this hash instead of bot's token.

**Comment by heyqbnk** [comment]
Your feature is Implemented in `@tma.js/init-data-node@1.4.0`

**Comment by snimshchikov** [comment]
You are the best, thank you!
