### ISSUE TITLE
[Bug]: Uncaught Error: Unable to retrieve launch parameters from any known source. when I open my app outside TG environment.

### ISSUE THREAD

**Issue by zhanghaoxu** [Telegram-Mini-Apps/tma.js#373]
### Telegram Application

Other

### Describe the Bug

this package do not support web app outside TG can you try to have a support?

### To Reproduce

when you open a tg mini app include this package in browser,you will have the problem.

### Expected Behavior

i can open my app

**Comment by alagunoff** [comment]
I think [this](https://docs.telegram-mini-apps.com/packages/tma-js-sdk/environment)'ll help

**Comment by chang0022** [comment]
I used this way
```
let shouldMock = false;
try {
  retrieveLaunchParams();
} catch (e) {
  shouldMock = true;
}

if (shouldMock) {
 mock something
}
```
https://github.dev/Telegram-Mini-Apps/tma.js/blob/9b916a254b27f65263baaf231a7c88164fefc5bd/playgrounds/react/src/mockEnv.ts

**Comment by heyqbnk** [comment]
You can start from here:
https://github.com/Telegram-Mini-Apps/reactjs-template/blob/master/src/index.tsx#L7
