### ISSUE TITLE
[Bug]: Unhandled exception while closing the qr scanner screen

### ISSUE THREAD

**Issue by val-o** [Telegram-Mini-Apps/tma.js#376]
### Telegram Application

Telegram for iOS

### Describe the Bug

Unhandled exception while closing the qrScanner screen, opened by using useQrScanner hook inside react app
This error prevents subsequent openening of qrScanner, because SDK thinks it's still open
```
Unhandled Promise Rejection: Error: QR scanner is already opened.
```

Here is an error snippet
```
"An error occurred processing the \"scan_qr_popup_closed\" event from the Telegram application. Please, file an issue here: https://github.com/Telegram-Mini-Apps/tma.js/issues/new/choose"
{eventType: "scan_qr_popup_closed", eventData: null}
TypeError: undefined is not an object (evaluating 'i.event') — 
```

<img width="1184" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/9393189/49014400-9a02-4b29-bf5b-5a6d6211af56">

### To Reproduce

```
  const qrScanner = useQRScanner()
return <button onClick={() => { qrScanner.open()}}></button>

```
- I click on button and qr screen opens
- I close native qr screen
- I click on button again and  qr screen opens

### Expected Behavior

- I click on button and qr screen opens
- I close native qr screen
- I click on button again and nothing happens due to excpetion

**Comment by heyqbnk** [comment]
Fixed. Thank you for the report!
