### ISSUE TITLE
[Bug]: The link 'potential issues' in the MOTIVATION.md is broken

### ISSUE THREAD

**Issue by kubk** [Telegram-Mini-Apps/tma.js#379]
### Telegram Application

Other

### Describe the Bug

It seems like the 'potential issues' link here leads to a section that no longer exists:

https://github.com/Telegram-Mini-Apps/tma.js/blob/master/MOTIVATION.md#unproductive-package-format

### To Reproduce

1. Go to https://github.com/Telegram-Mini-Apps/tma.js/blob/master/MOTIVATION.md#unproductive-package-format
2. Click on 'potential issues'
3. Nothing happens

### Expected Behavior

It should lead somewhere or it shouldn't be a link

**Comment by heyqbnk** [comment]
Fixed. Thank you!
