### ISSUE TITLE
[Bug]: Error: Unable to retrieve launch parameters from any known source.

### ISSUE THREAD

**Issue by oceanlvr** [Telegram-Mini-Apps/tma.js#383]
### Telegram Application

Telegram for iOS, Telegram Desktop

### Describe the Bug

1. Depoly to vercel 
2. npm run build && npm run preview
``` sh
An unhandled error occurred:
Unable to retrieve launch parameters from any known source.
```

3.  it seems that @tma.js/sdk-react is not working with vercel vite dploy
```
 import {
  bindMiniAppCSSVars,
  bindThemeParamsCSSVars,
  bindViewportCSSVars,
  initNavigator,
  useLaunchParams,
  useMiniApp,
  useThemeParams,
  useViewport,
} from '@tma.js/sdk-react';
```

![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/36698124/c4ae0ede-4dd9-4f5c-bc5c-30b1ae00eb69)

![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/36698124/06f1f8d5-d654-4e2f-8998-8dea6d2de3d1)

### To Reproduce

1. Go to vercel
2. Click on deploy
3. not working for template https://github.com/Telegram-Mini-Apps/reactjs-template/blob/master/src/index.tsx#L7
4. See error 404(vercel)
![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/36698124/8c8b0d11-021b-4896-a37b-2c8a7ee4f4d5)

### Expected Behavior

deploy success.
not 404 not found https://frontend-gold-pi.vercel.app/
![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/36698124/ed3d0354-d493-41ff-b0da-f3abe8067e7e)

**Comment by heyqbnk** [comment]
You must run the application inside Telegram.

**Comment by oceanlvr** [comment]
<img width="442" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/36698124/f45017bb-8f2b-47aa-bb9e-9341021cb8f1">

@heyqbnk same issue

**Comment by heyqbnk** [comment]
You actually have a different issue now

**Comment by oceanlvr** [comment]
Issue solved. It caused by vercel
