### ISSUE TITLE
[Feature]: how to expand mini app after open

### ISSUE THREAD

**Issue by fukemy** [Telegram-Mini-Apps/tma.js#452]
### Is your feature request related to a problem? Please describe.

Yes, the mini app open in halfscreen instead of fullscreen

### Describe the solution you'd like

I want to open in fullscreen state

### Describe alternatives you've considered

I saw `web_app_expand` method but I do not know how to use it

**Comment by HieuTVGCH200824** [comment]
This can be achieved with Viewport 
``[https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/components/viewport#viewport](url)
