### ISSUE TITLE
"Async call timeout exceeded. Timeout: 1000" error in Telegram web

### ISSUE THREAD

**Issue by kiran-venugopal** [Telegram-Mini-Apps/tma.js#93]
**Describe the bug**
Getting "Async call timeout exceeded. Timeout: 1000 " error while SDK initialisation in telegram web app (https://web.telegram.org/k)

**To Reproduce**
1. import and use SDKProvider component
2. open mini app in telegram web app

**Expected behavior**

init should be successful as in android telegram app 
![Screenshot 2023-09-23 112318](https://github.com/Telegram-Mini-Apps/tma.js/assets/62516337/1cd34f8f-e6a4-43e2-9d37-860332ce4cfb)

**Comment by heyqbnk** [comment]
1. Do you open your app inside Telegram?
2. Do you use the latest version of Telegram app?

This problem previously occurred due to incorrect behavior of Telegram application not supporting Telegram Web Apps methods such as `web_app_request_theme` or `web_app_request_viewport`

**Comment by kiran-venugopal** [comment]
Seems like telegram K version is not supported, i think that is the issue

**Comment by heyqbnk** [comment]
Hom is it connected with Telegram for Android?

**Comment by heyqbnk** [comment]
Solution for your problem is in production. Please, use the latest version of SDK
