### ISSUE TITLE
Cache headers recommendations

### ISSUE THREAD

**Issue by stels-cs** [Telegram-Mini-Apps/tma.js#99]
I ran into a problem that my HTML file was infinitely cached. The problem disappeared after I uninstalled and reinstalled Telegram. It looks like we need to add headers that directly affect the caching of HTML files.

https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers/2068407#2068407

**Comment by heyqbnk** [comment]
Any ideas on where to place this documentation? Current state:
https://docs.telegram-mini-apps.com/

I assume, we could insert it in "Guides" section
